PMS_Main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='Home'),
    path('registro/', views.registro),
    path('dashboard/', include('AdminHome.urls')),
    path('Eventos/', include('Eventos.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('inventario/', include('Inventario.urls')),
    path('empleados/', include('crud_empleados.urls')),
    path('huespedes/', include('Clientes.urls')),
    path('sugerencias/', include('Sugerencias.urls')),
    path('restaurante/', include('Restaurante.urls')),
    path('carro/', include('carro.urls')),
    path('habitaciones/', include('habitaciones.urls')),
    path('reservas/', include('reservas.urls')),
    path('cerrar_sesion/', views.cerrar_sesion)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Restaurante/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.mainRestaurante, name="main"),
    path('agregarComida/', views.Comida, name="comida"),
    path('restaurante/', views.Restaurante, name="restaurante"),
    path('uptPlato/<id>/', views.uptPlatillo, name="update"),
    path('dltPlato/<id>/', views.dltPlatillo, name="delete"),
    path('finalizar/', views.finalizar, name="finalizar")
]

carro/urls.py
from django.urls import path

from . import views

app_name = "carro"

urlpatterns = [


    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),


]

Restaurante/models.py
from django.db import models
# Create your models here.

seccion = [
    [0, "Desayuno"],
    [1, "Almuerzo"],
    [2, "Postre"],
    [3, "Bebida"],
    [4, "Cena"],
]


class Producto(models.Model):
    Producto = models.CharField(max_length=20)
    Descripcion = models.TextField()
    TipoProducto = models.IntegerField(choices=seccion)
    Precio = models.IntegerField()
    Promocion = models.BooleanField(default=False)
    Imagen = models.ImageField(upload_to="restaurante", null=True)

    def __str__(self):
        return self.Producto

Restaurante/forms.py
from django import forms
from .models import Producto


class ProductoFrm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'

Restaurante/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Producto
from .forms import ProductoFrm
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import Http404

# Create your views here.


@login_required
def mainRestaurante(request):

    platillo = Producto.objects.all()

    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(platillo, 5)
        platillo = paginator.page(page)
    except:
        raise Http404

    return render(request, "Main.html", {
        'entity': platillo,
        'paginator': paginator
    })


def Restaurante(request):

    menu = Producto.objects.all()

    return render(request, "Restaurante.html", {
        'menu': menu
    })


@login_required
def Comida(request):

    data = {
        'restaurante': ProductoFrm()
    }

    if (request.method == "POST"):
        osvell = ProductoFrm(data=request.POST, files=request.FILES)
        if osvell.is_valid():
            osvell.save()
            messages.success(request, "Plato Agregado Con Exito")
            return redirect("main")

    return render(request, "Agregar.html", data)


@login_required
def uptPlatillo(request, id):

    plato = get_object_or_404(Producto, id=id)

    data = {
        'restaurante': ProductoFrm(instance=plato)
    }

    if (request.method == "POST"):
        rest = ProductoFrm(data=request.POST,
                           instance=plato, files=request.FILES)
        if rest.is_valid():
            rest.save()
            messages.success(request, "Plato Actualizado Con Exito")
            return redirect("main")

    return render(request, "Actualizar.html", data)


@login_required
def dltPlatillo(request, id):
    plato = get_object_or_404(Producto, id=id)
    plato.delete()
    messages.success(request, "Plato Eliminado Con Exito")
    return redirect('main')


def finalizar(request):
    return render(request, "Compra.html")

Restaurante/templates/Actualizar.html
{% extends 'ZK/navbar2.html' %}

{% block content %}

{% load crispy_forms_filters %} 
{% load crispy_forms_tags %}

<div id="page-wrapper" >
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <h1>Restaurante <small>Actualizar Platillo</small></h1>                
            </div>
        </div>
         <!-- /. ROW  -->
         <hr />
                         
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{restaurante | crispy}}
        <input type="submit" class="btn btn-primary" value="Actualizar">
    </form>
</div>
</div>

{% endblock %}

Restaurante/templates/Agregar.html
{% extends 'ZK/navbar2.html' %}

{% block content %}

{% load crispy_forms_filters %} 
{% load crispy_forms_tags %}

<div id="page-wrapper" >
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <h1>Restaurante <small>Agregar Platillos</small></h1>                
            </div>
        </div>
         <hr />
                         
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{restaurante | crispy}}
        <input type="submit" class="btn btn-primary" value="Agregar">
    </form>
</div>
</div>

{% endblock %}

Restaurante/templates/Compra.html
<h2>Factura</h2>
{% include "carro/widgets2.html" %}

Restaurante/templates/Main.html
{% extends 'ZK/navbar2.html' %}

{% load humanize %}

{% block content %}

<div id="page-wrapper" >
        {% if messages %}
            {% for m in messages %}
                <div class="alert alert-success" role="alert">
                    {{m}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">X</button>
                </div>         
            {% endfor %}
        {% endif %} 
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <h1>Hotel Las Lomas <small>(Restaurante)</small></h1>                
            </div>
        </div>
         <hr />
                         
    <div class="row">
        <div class="col-md-6 col-sm-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Menu
                </div>
                <div class="panel-body">
                    <p>Menu del restaurante para comprobar que los platillos se esten cargando correctamente</p>
                </div>
                <div class="panel-footer">
                    <button type="button" class="btn btn-primary btn-lg"><a href="{% url 'restaurante' %}" style="text-decoration: none; color: #ffffff ;">Restaurante</a></button>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-sm-6">
            <div class="panel panel-success">
                <div class="panel-heading">
                    Agregar Platillos
                </div>
                <div class="panel-body">
                    <p>Agregar platillos al menu, notificar los ingredientes para alertar a los clientes para evitar reacciones alergicas</p>
                </div>
                <div class="panel-footer">
                    <button type="button" class="btn btn-success btn-lg"><a href="{% url 'comida' %}" style="text-decoration: none; color: #ffffff ;">Agregar</a></button>
                </div>
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Producto</th>
                    <th>Tipo</th>
                    <th>$</th>
                    <th>Promocion</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for c in entity %}
                <tr>
                <td>{{forloop.counter}}</td>
                <td>{{c.Producto.title}}</td>
                    {% if c.TipoProducto == 0 %}
                        <td style="background: rgb(111, 204, 111); color: #ffff ;"><strong>Desayuno</strong></td>
                    {% elif c.TipoProducto == 1 %}
                        <td style="background: rgb(255, 255, 95); color: #000 ;"><strong>Almuerzo</strong></td>
                    {% elif c.TipoProducto == 2 %}
                        <td style="background: crimson; color: #ffff ;"><strong>Postre</strong></td>
                    {% elif c.TipoProducto == 3 %}
                        <td style="background: burlywood; color: #000 ;"><strong>Bebida</strong></td>
                    {% elif c.TipoProducto == 4 %}
                        <td style="background: rgb(7, 18, 175); color: #ffff ;"><strong>Cena</strong></td>
                    {% endif %}
                <td>{{c.Precio | intcomma}}</td>
                    {% if c.Promocion == False %}
                        <td style="background: crimson; color: #ffff ;">No</td>
                    {% elif c.Promocion == True %}
                        <td style="background: rgb(111, 204, 111); color: #ffff ;">Si</td>
                    {% endif %}
                <td><div>
                    <button type="button" class="btn btn-warning"><a href="{% url 'update' c.id %}" style="text-decoration: none; color: #ffffff ;"><i class="fas fa-sync-alt"></i></a></button>
                    <button type="button" class="btn btn-danger btnEliminacion"><a href="{% url 'delete' c.id %}" style="text-decoration: none; color: #ffffff ;"><i class="fas fa-trash-alt"></i></a></button>
                </div></td>
               </tr> 
            {% endfor %}
        </tbody>
    </table>
    <div>
        <center>{% include 'paginator.html' %}</center>
    </div>
    </div><hr>
</div>
</div>
{% endblock %}

Restaurante/templates/Restaurante.html
{% extends 'ZK/navbar.html' %}

{% load static %}
{% load humanize %}

{% block restaurante %}

  <section class="offer_section layout_padding-bottom">
    <div class="offer_container">
      <div class="container ">
        <div class="row">
          {% for J in menu %}
          {% if J.Promocion == True %}
          <div class="col-md-6  ">
            <div class="box ">
              <div class="img-box">
              {% if J.Imagen %}
                <div class="img-box">
                  <img src="{{ J.Imagen.url }}" alt="">
                </div>
              {% endif %}
              </div>
              <div class="detail-box">
                <h5>
                  Promocion del Dia
                </h5>
                <h6>
                  <span>20%</span> Off
                </h6>
                <a href="{% url 'carro:agregar' J.id %}" style="text-decoration: none; color: #ffffff ;"><i class="fa fa-shopping-basket"></i></a>
              </div>
            </div>
          </div>
          {% endif %}
          {% endfor %}
        </div>
      </div>
    </div>
  </section>

  <section class="food_section layout_padding-bottom">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Menu del Dia
        </h2>
      </div>

      <ul class="filters_menu">
        <li class="active" data-filter="*">Todo</li>
        <li data-filter=".0">Desayunos</li>
        <li data-filter=".1">Almuerzos</li>
        <li data-filter=".4">Cenas</li>
        <li data-filter=".3">Bebidas</li>
        <li data-filter=".2">Postres</li>
      </ul>

      <div class="filters-content">
        <div style="float:right;">
          {% include "carro/widgets.html" %}
        </div>
        <div class="row grid">
          {% for m in menu %}
            <tr>
              <div class="col-sm-6 col-lg-4 all {{m.TipoProducto}}">
                <div class="box">
                  <div>
                    {% if m.Imagen %}
                      <div class="img-box">
                        <img src="{{ m.Imagen.url }}" alt="">
                      </div>
                    {% endif %}
                    <div class="detail-box">
                      <h5>
                        {{m.Producto | title}}
                      </h5>
                      <p>
                        {{m.Descripcion}}
                      </p>
                      <div class="options">
                        <h6>
                          ${{m.Precio | intcomma }}
                        </h6>
                          <a href="{% url 'carro:agregar' m.id %}" style="text-decoration: none; color: #ffffff ;"><i class="fa fa-shopping-basket"></i></a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </tr>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>

{% endblock %}

Restaurante/templates/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
{% endif %}